---

cs_setup_dir: ~/setup-files/cs-setup
cs_operator_name: ibm-common-service-operator
cs_operand_namespace: ibm-common-services
cs_operator_project_name: common-service
cs_subscription_channel: stable-v1
cs_subscription_strategy: Automatic
cs_operator_catalog_image: "quay.io/opencloudio/ibm-common-service-catalog:latest"
cs_operand_list: ["ibm-cert-manager-operator","ibm-mongodb-operator","ibm-iam-operator","ibm-monitoring-exporters-operator","ibm-monitoring-prometheusext-operator","ibm-monitoring-grafana-operator","ibm-healthcheck-operator","ibm-management-ingress-operator","ibm-metering-operator","ibm-commonui-operator","ibm-ingress-nginx-operator","ibm-platform-api-operator"]
storageclass_name: nfs-storage-provisioner

