---
- name: Installation of the Node Feature Discovery Operator
  hosts: bastion
  tasks:
  - name: Include the global-secret-update role
    include_role:
        name: security_compliance/global-secret-update
    when: nfd_catalogsource != "" and nfd_catalogsource != None

- name: Include the Node Feature Discovery Operator role
  hosts: bastion
  roles:
  - openshift_operators/ocp-nfd-operator
