---
- name: Include the Vertical Pod Autoscaler Operator role
  hosts: bastion
  tasks:
  - name: Include the global-secret-update role
    include_role:
      name: security_compliance/global-secret-update
    when: vpa_catalogsource_image != "" and vpa_catalogsource_image != None and vpa_cleanup == false

  - name: Include the Vertical Pod Autoscaler Operator role
    include_role:
      name: openshift_operators/ocp-vpa-operator
